### ISSUE TITLE
Add task pipelines

### ISSUE THREAD

**Issue by mudler** [MottainaiCI/mottainai-server#11]

**Comment by mudler** [comment]
Groups: 
```yaml
pipeline_name: "Test Pipeline"
concurrency: 1
group:
  - "test"
  - "test2"
  - "test3"

tasks:
  test:
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    image: sabayon/base-amd64
    script:
      - echo 'hello'
      - exit 1
    task: docker_execute
  test2:
    image: sabayon/base-amd64
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    script:
      - echo 'hello world!'
    task: docker_execute
  test3:
    image: sabayon/base-amd64
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    script:
      - echo 'hello from 3'
    task: docker_execute
```

Chains: 
```yaml
pipeline_name: "Test Pipeline"
chain:
  - "test"
  - "test2"
  - "test3"

tasks:
  test:
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    image: sabayon/base-amd64
    script:
      - echo 'hello'
      - exit 1
    task: docker_execute
  test2:
    image: sabayon/base-amd64
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    script:
      - echo 'hello world!'
    task: docker_execute
  test3:
    image: sabayon/base-amd64
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    script:
      - echo 'hello from 3'
    task: docker_execute
```

Chords: 
```yaml
pipeline_name: "Test Pipeline"
concurrency: 1
group:
  - "test"
  - "test2"

chord:
  - "test3"

tasks:
  test:
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    image: sabayon/base-amd64
    script:
      - echo 'hello'
      - exit 1
    task: docker_execute
  test2:
    image: sabayon/base-amd64
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    script:
      - echo 'hello world!'
    task: docker_execute
  test3:
    image: sabayon/base-amd64
    source: https://github.com/Sabayon/community-repositories
    directory: /pantheon-desktop
    script:
      - echo 'hello from 3'
    task: docker_execute
```
