### ISSUE TITLE
Improve task namespace option for handle multiple namespace in different path

### ISSUE THREAD

**Issue by geaaru** [MottainaiCI/mottainai-server#60]
The idea is to add the option `namespace_merged` (with default true) that merge files from different namespace like is done now with a value like this:
```yaml
namespace: "myns1,myns2"
namespace_merged: true
artefact_path: /artefacts
```
If `myns1` has files `x1, x1b` and `myns2` has files `x2, x2b` then inside the task under the path `/artefacts` files will be:
```sh
$# ls /artefacts
x1 x1b x2 x2b
```
If the value of `namespace_merged` is equal to `false` then the artefact path will be:
```sh
$# ls /artefacts/myns1/
x1 x1b
$# ls /artefacts/myns2/
x2 x2b
```
