### ISSUE TITLE
Add filter to namespace

### ISSUE THREAD

**Issue by geaaru** [MottainaiCI/mottainai-server#61]
For improve throughput and reduce the download of unused files will be possible to define filter on namespaces:
```yaml
artefact_path: /artefacts
namespace: "myns"
namespace_filters:
    - *.meta.yaml
tag_namespace: "tag1"
artefact_push_filters:
    - repository.yaml
```
